#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

sudo: required

group: deprecated-2017Q3

language: scala
scala:
   - 2.11.8

services:
  - docker

notifications:
  email: false
  slack:
    rooms:
      - secure: "Rrj5ya7JV7bfgW3GXZpuRsX2e9/qsTpLLVZAzgq2Z3xW/IVAqeAM8DDR0tjPbR7Nou0RpPtE/ynkps4Qd6CGTBiCULpcGi2cXJ+p35WvaweWlFIKU0Vam9iEWXQ+bG1LwB61LrSmD7DJvOxkZiwtagqUfYLhVeD1WfgcWc/lj0F0julCScujqqJbj/jUnlkSm6VJz9m11NQkvZZ+YFgNYCPAQRmSh59K0ELximJ54C4/af05YHq6QLWUh/2Eoa68p3XzQyONtteMRvbAJgmMGIijQsKa+ZELrZPjz/5EplMA+FEUjoW6tn3NQjQgZOdDHq3fEbnuit0OOBMRu5QhYT0MjV6QJANYmJU2QqVoDubgTtQSeHJNYoM1fI15yfuSCJg+H6FnI0ncXRB3zz7EZ3zksKKeWZ20NQVKBNCYRNIBC8Im3ff8TbZdulH/Qk/NEeOJwpgm8yfUqUqLu3dt13KT0JdxEcQeOX5lRmz+XBrN6C52/fX0NstO2OCxpKhKcq2+B/Y3mCn6ywqAiTtaLyhPrW08cCB3sBX8y5/Q3do8KPWO1MiBc/K+qtK481bnkh41DaLasqpltpEkFhCW/Udl8iuYEkMWZwNdhEUv6uuPiKF9da4FJkhIV3xVYOzrjF6xR2BtmHVGnCVMMoCUQo9tG8K9tOf+omH+KezZPuw="
      - secure: "WgdL9/Z/9+rl6edh+mqDiO0mx8JpxYwIrudYwuZUZ7d/9oUzS8Miid7au7Y1PP0CVPVDEvastw6+NnIVA/BIHTBNj488dTeNXumaaNQlaTTvaI9OLN1w3+GVVFuF64gmJ6I2T6x+qxqlYOwQhyZ8jZEJUXQ3VwE6DPz+KNqpBy+6GgWEvi+2lgGhc2Ko3SPAtcDWAdE6t8ELaO2uLh/JU60ndAi4yT297fOfwWi4I1aee5a+LajbJN6Mz89o5o0Y2GHV83a3D/ablt1CH3kRSErqLV3HDbt5eRR4yFhTPpbZG8yeWcZkP0oKyt3QqSen1paiEeqr7R9OspDf2OLSlWx7TGm/BnNW/3YRI3+gUPHqaJPCLldNRWnbYYd0RFGjVOfVOoYhAWAMdkWT48jX3YGE1LaZ0SwlxpMy5Fpj8Q22SVXY51o5Pw1UomUhGz2Hjfj8b0WbkWQ+q5qpgR8/z4Zfz5i3MY03mQNzeXs4Z9NoznIiz+9eQVpi4tkjUH3o2AFi6VXTdire61vfhFG3iYYqo2woKwNWOVaK/g0l13EVWiK62YxQEUZJbmhLb6VQrABrB2FCWl/+zZOOR3OUeie3AgAmxEwjxN9Y1IgMy0bJWEZ+ECf//39XMgj5Ys/gPsejDjPsWxhO6cuNtGq9K6RsPij1a0E+01JcyrNyNX0="
    on_pull_requests: false
    on_success: change
    on_failure: always
  webhooks:
    urls:
      secure: "WSg7mxT+VzZ/a7wUp9iW+AzRSdUfw4O//PM29lU2Hk7ULmp5kFfKfYIXB2t0l66Wq3XUkTFfwPPQ5fTOYx7c3m3jVquY4LkFCfvDtNCwRPvxhyGSOuz9ywUeY9LlU+k26ZzBagH4WDTju3k03bCq1n2hd86OYKaF3H6M+9YKcSZznxgEMwg9fDjEdK6HXUc8T3SAW1BTMsOY15Y1OuwpRcAzojdEacRTPhbzM/Z0jYXjtgHYb/Jcb7v4vZqBvKZiH3Y4f2pZEdo8Ao56QYMkwTagsajaWfiYdrITj/MAVP8tdaAnkxXB+ZZxU6NSbSF9NsXl9BJE0m48bdtAltnwP3ANpKCxrllFa8GaqM4E8SGR3wFrXBS7K87u30YpNJQmQGEXl/hv8DiduYU+8yDMTxF/rbAprrs+vUVK1cQYMiH14sM1IITkAOviFqKZ99zHkHGetEhIpr51rMXuZ4To6IgXW7MuLm4lJSnTLH4GyELxWb0aK3s9cVRUNLR9KKZ42PnJ+R7JAEBYE9kPyeALR19VKjw1s13axGYk50acsmnOEnrZlgYvHG3pfsGrJ0OJhbK/G7JlVST7whJAs+oYj1nX79EPGeXbdpx0AFpShfE+xHlsOZ5ANq1h8gksE1D8cdc7XSNC2rvW+iANsG6GhNw5I3EOPGT+9SCg1HAlPdc="

before_install:
  - pip install --upgrade pip setuptools six
  - pip3 install --upgrade pip setuptools six
  - ./tools/travis/flake8.sh  # Check Python files for style and stop the build on syntax errors

install:
  - ./tools/travis/setup.sh

script:
  - ./tools/travis/build.sh
  - ansible-playbook -i ansible/environments/local ansible/logs.yml # collect logs regardless of build exit
  - ./tools/travis/box-upload.py "$TRAVIS_BUILD_DIR/logs" "$TRAVIS_BUILD_ID-$TRAVIS_BRANCH.tar.gz"

env:
  global:
    secure: "GsECne3l5Jd9dLetpTPU4UPG1Uv1I7tV1BzifHX9pYlUIJ0PWpxSgNEBib25gtr426mpmnCNjBG5t/nIHxJk/F2Xg9/YJVazB1JcuruV0baKDkb9jRISmgYyEE5d4oHrhmcf+YrDCkOYzZQqVXwtH6ENINQnkF6cOadYtb0VS2t/1CS15aCOsqcrq5gGPb0TqxoPzNi1BklBjRzCyPE+IC7Ihut2DtRgxptcoi4zqQu4eaD+RMb4Axn8RVWmRLMTmS1b69QJ9+MshCafYyV+1/AHvXiZHv2wQ2YTNARdNCKxVgEvqg0I+NafEaIYrs7RVmdSxdUoyekJ3y9XzABRMVJIiAzDFJdQEUJs8SBnWYiSDUv9mjoNqR3q7sm1c0AacUkm6qp2cy0e91fnIbFIaYcRzTI9ZtFDkEtllqYm65ZwsFFX++ge7itmXKoo/vzvDOX5iLkuMl4zH015ASDvRxChHNBhFLXu/8w+Tudpb5FVJQuhqh2a5bwvPrpsyOMAt300oFJMyZGVkXzucFQUXd7G0fLj2CZE1tMQsAGDrX4Hs1GMFOLp7NHFFit+SGXSqTk6Ff2Lr3kQxZMy0L22/tYx0LWZ+mFiNLp2ij+d/+rMu7gqjV13J8iWBu0mcwOpKLnWIqEZGVE59tZ+NRHtaJUu0y8ln6p8/2Dz380Eow0="
    secure: "RT0X4QAGLgDbHWGsJkxtMTK7RMWF17Fd3d6c+RwgM4Vl00mEIcTUO6Xqf30rIjvNOOIdGgw/p6TXDuGh2iHeacaStYCp078XoO9RrPR8+a/nZULJJDrDbrznxljb0DD8LXZdOof/GcOv5W+VZVADt+ozbt9gtEtBmoiVPrTju7bn6YEXm3C+mlazNtOEwV5ZVFe5EVZkGk+YHIm2hkPl3cSiOh9qV3s+tIKS1T3rZ2wEgvvYvWdPxtDSU7/6DhD0Oof06EU5/VBoP3wLi6JhIcLorJHrZzGm4Pa9CDMP2Wjfq8aoYM1h0gXU8vZBSsjUezJZ6YNeHwF/57LnPCkHV93QWF1FCIq8oIJtYfrTqwwLJKg1Gm8nQqZmlqv2/2txhJQHBr0tmGAU2x7FJmIvg2Cp2WIkWYfZ7R6EanK+bMOiTtmv1EtvLrrGC5WZ86Ka3JjL0YXpYv3t9tVRKnM5bmVTjzKY4cDbqYAk+FETKT1A7ZQ4IxskXk/4vQhnLD1cT9MbzxehLhy++N8tB4wJHsjWGHuZXZxzkRn5wzCg18Amnv2SwzXrnM2JkVsdZ4/jc+fMH0xCQ5wm2cglg625QQrKXZXFtCbiq1R2nH2WX9Bw1V7DSjyOIJ/TrL/B1ktH4pRKKCEn9QZqwJTS28inao2mm6m63dK1Cgi8a0hF1jg="
